# your-git-repo/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-workflow-templates
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/argocd-argo-workflow/argo-workflow-template.git'
    targetRevision: main
    path: workflows
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
